/* AUTO-GENERATED BY Z-SCANNER - DO NOT EDIT */
#ifndef Z_REGISTRY_H
#define Z_REGISTRY_H

/* Vectors */
#define Z_AUTOGEN_VECS(X) \
    X(int, Int) \

/* Lists */
#define Z_AUTOGEN_LISTS(X) \
    X(float, Float) \

/* Maps */
#define Z_AUTOGEN_MAPS(X) \
    X(int, const char*, StrMap) \

/* Stable Maps */
#define Z_AUTOGEN_STABLE_MAPS(X) \

/* Results */
#define Z_AUTOGEN_RESULTS(X) \
    /* No results found */

#endif // Z_REGISTRY_H
